version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: 'cinema_db'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
       - "127.0.0.1:5432:5432"
    volumes:
      - cinema_db:/var/lib/postgresql/data
volumes:
  cinema_db: